sonar.projectKey=lastmile-front
sonar.projectName=LastMile Frontend
sonar.projectVersion=1.0.0
sonar.organization=lastmileplatform

# Directorios a analizar
sonar.sources=src,app

# Exclusiones
sonar.exclusions=\
  **/node_modules/**,\
  **/.expo/**,\
  **/assets/**,\
  **/coverage/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Cobertura de tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=\
  app/**,\
  src/components/**,\
  src/providers/**,\
  src/modules/**/screens/**,\
  src/modules/**/components/**
sonar.coverage.inclusions=\
  src/services/api/**,\
  src/services/auth/**,\
  src/services/state/**,\
  src/modules/**/constants/**,\
  src/modules/**/utils/**,\
  src/types/**,\
  src/constants/**
sonar.cpd.exclusions=\
  src/modules/campaigns/**,\
  src/modules/campaigns/screens/DonorCampaignsScreen.tsx,\
  src/modules/campaigns/screens/OrganizerCampaignsScreen.tsx
# sonar.testExecutionReportPaths=coverage/test-report.xml

sonar.sourceEncoding=UTF-8
